/** Embedded, dependency-light OpenRouter pool console. */
export const ADMIN_HTML = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenRouter Proxy</title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
:root{--bg:#0b1020;--card:#151d34;--line:#2b3657;--text:#edf2ff;--muted:#9aa9ca;--accent:#7c9cff;--bad:#ff7892;--ok:#42d6a4}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,system-ui,sans-serif}.wrap{max-width:1180px;margin:auto;padding:28px 18px}h1,h2{margin:0}header,.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;justify-content:space-between}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px;margin-top:14px}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:14px}.stat{padding:13px;background:#11182b;border-radius:10px}.muted{color:var(--muted);font-size:12px}.value{font-size:22px;font-weight:700;margin-top:3px}input,textarea,select,button{border-radius:8px;border:1px solid var(--line);padding:9px;background:#0f1629;color:var(--text);font:inherit}textarea{width:100%;min-height:92px}button{background:var(--accent);border:0;cursor:pointer;font-weight:600}button.danger{background:var(--bad)}button.ghost{background:transparent;border:1px solid var(--line)}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line);white-space:nowrap}th{color:var(--muted);font-size:12px}.pill{padding:3px 7px;border-radius:99px;background:#243151}.active{background:#174b3c}.exhausted,.deprecated{background:#5b2638}.charts{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.hidden{display:none}#login{max-width:420px;margin:13vh auto}@media(max-width:750px){.stats,.charts{grid-template-columns:1fr 1fr}table{font-size:12px}}
</style></head><body><main class="wrap">
<section id="login" class="card"><h1>OpenRouter Proxy</h1><p class="muted" data-i="loginHint">Enter the ADMIN_KEY. It is never stored beyond this browser session.</p><div class="row"><input id="key" type="password" placeholder="ADMIN_KEY"><button onclick="login()" data-i="login">Login</button></div><p id="loginMsg"></p></section>
<section id="app" class="hidden"><header><div><div class="muted">D1 MULTI-KEY POOL</div><h1>OpenRouter Proxy</h1></div><div class="row"><button class="ghost" onclick="toggleLang()">EN / 中文</button><button class="ghost" onclick="loadAll()" data-i="refresh">Refresh</button><button onclick="sync()" data-i="syncAll">Sync all</button><button class="ghost" onclick="logout()" data-i="logout">Logout</button></div></header>
<div class="stats" id="stats"></div>
<section class="card"><div class="row"><h2 data-i="poolSettings">Pool settings</h2><button onclick="saveSettings()" data-i="save">Save</button></div><div class="row" style="margin-top:12px"><label data-i="strategy">Strategy <select id="strategy"><option>most_remaining</option><option>least_requests</option><option>round_robin</option><option>lru</option></select></label><label data-i="syncInterval">Sync seconds <input id="interval" type="number" min="900"></label><label data-i="maxFailures">Max failures <input id="failures" type="number" min="1"></label><label data-i="quotaLead">Quota lead seconds <input id="lead" type="number" min="0"></label></div></section>
<section class="card"><div class="row"><h2 data-i="addKeys">Add keys</h2><button onclick="addKeys()" data-i="add">Add</button></div><textarea id="keys" placeholder="sk-or-...&#10;sk-or-..."></textarea><input id="note" placeholder="Note (optional)"></section>
<section class="card"><div class="row"><h2 data-i="analytics">Analytics</h2><button class="ghost" onclick="document.getElementById('charts').classList.toggle('hidden')" data-i="toggle">Toggle</button></div><div id="charts" class="charts"><canvas id="credits"></canvas><canvas id="states"></canvas><canvas id="countries"></canvas><canvas id="picks"></canvas><canvas id="endpoints"></canvas><canvas id="results"></canvas></div></section>
<section class="card"><h2 data-i="keys">Keys</h2><div style="overflow:auto"><table><thead><tr><th>Key</th><th data-i="status">Status</th><th data-i="remaining">Remaining</th><th data-i="usage">Usage</th><th data-i="requests">Picks</th><th data-i="lastEndpoint">Last endpoint</th><th data-i="lastResult">Last result</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></section></section></main>
<script>
let adminKey=sessionStorage.getItem('or-admin')||'',data={},charts={},zh=false;
const i18n={login:'登录',loginHint:'输入 ADMIN_KEY；仅保存在此浏览器会话中。',refresh:'刷新',syncAll:'同步全部',logout:'退出',poolSettings:'池设置',save:'保存',strategy:'策略',syncInterval:'同步秒数',maxFailures:'最大失败次数',quotaLead:'配额提前探测秒数',addKeys:'添加密钥',add:'添加',analytics:'分析',toggle:'展开/收起',keys:'密钥',status:'状态',remaining:'剩余额度',usage:'已用额度',requests:'选择次数',lastEndpoint:'最后端点',lastResult:'最后结果',enable:'启用',delete:'删除'};
function esc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function t(k){return zh?(i18n[k]||k):({login:'Login',loginHint:'Enter the ADMIN_KEY. It is never stored beyond this browser session.',refresh:'Refresh',syncAll:'Sync all',logout:'Logout',poolSettings:'Pool settings',save:'Save',strategy:'Strategy',syncInterval:'Sync seconds',maxFailures:'Max failures',quotaLead:'Quota lead seconds',addKeys:'Add keys',add:'Add',analytics:'Analytics',toggle:'Toggle',keys:'Keys',status:'Status',remaining:'Remaining',usage:'Usage',requests:'Picks',lastEndpoint:'Last endpoint',lastResult:'Last result',enable:'Enable',delete:'Delete'}[k]||k)}
async function api(path,opt={}){let r=await fetch(path,{...opt,headers:{'content-type':'application/json','x-admin-key':adminKey,...(opt.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({error:r.statusText}))).error||r.statusText);return r.json()}
async function login(){adminKey=document.getElementById('key').value.trim();try{await api('/api/auth',{method:'POST'});sessionStorage.setItem('or-admin',adminKey);document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');loadAll()}catch(e){document.getElementById('loginMsg').textContent=e.message}}
function logout(){sessionStorage.removeItem('or-admin');location.reload()}function toggleLang(){zh=!zh;document.querySelectorAll('[data-i]').forEach(x=>x.textContent=t(x.dataset.i));render()}
async function loadAll(){try{let [k,s]=await Promise.all([api('/api/keys'),api('/api/stats')]);data={...k,stats:s.stats};render()}catch(e){alert(e.message)}}
function money(v){return '$'+Number(v||0).toFixed(4)}
function render(){let s=data.stats?.external||{};document.getElementById('stats').innerHTML=[['Keys',s.keyCount||0],['Healthy',s.healthy||0],['Limit',money(s.creditLimit)],['Used',money(s.creditUsage)],['Remaining',money(s.creditRemaining)]].map(x=>'<div class="stat"><div class="muted">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('');let c=data.settings||{};strategy.value=c.strategy||'most_remaining';interval.value=c.usageSyncIntervalSecs||86400;failures.value=c.maxNetworkFailures||5;lead.value=c.quotaProbeLeadSecs||3600;rows.innerHTML=(data.keys||[]).map(k=>'<tr><td title="'+esc(k.note)+'">'+esc(k.mask)+'<br><span class="muted">'+esc(k.label||'')+'</span></td><td><span class="pill '+esc(k.status)+'">'+esc(k.status)+'</span></td><td>'+money(k.creditRemaining)+'</td><td>'+money(k.creditUsage)+'</td><td>'+k.requestCount+'</td><td>'+esc(k.lastCallEndpoint||'—')+'</td><td>'+esc(k.lastCallStatus||'—')+'</td><td><button onclick="reactivate('+JSON.stringify(k.apiKey)+')">'+t('enable')+'</button> <button class="danger" onclick="removeKey('+JSON.stringify(k.apiKey)+')">'+t('delete')+'</button></td></tr>').join('');draw()}
function chart(id,type,labels,values,label){charts[id]?.destroy();charts[id]=new Chart(document.getElementById(id),{type,data:{labels,datasets:[{label,data:values,backgroundColor:['#7c9cff','#42d6a4','#ffbd59','#ff7892','#b391ff','#5bd1ff']}]},options:{plugins:{legend:{labels:{color:'#edf2ff'}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#9aa9ca'}},y:{ticks:{color:'#9aa9ca'}}}}});}
function pairs(o){return [Object.keys(o||{}),Object.values(o||{})]}
function draw(){let u=data.stats?.upstream||{},by=u.byKey||[];chart('credits','bar',by.map(x=>x.mask),by.map(x=>x.remaining),'Remaining USD');let a=pairs(u.status);chart('states','doughnut',a[0],a[1],'Status');a=pairs(u.countries);chart('countries','doughnut',a[0],a[1],'Country');chart('picks','bar',by.map(x=>x.mask),by.map(x=>x.picks),'Picks');a=pairs(u.lastEndpoint);chart('endpoints','doughnut',a[0],a[1],'Endpoint');a=pairs(u.lastResult);chart('results','doughnut',a[0],a[1],'Result')}
async function sync(){await api('/api/keys/sync',{method:'POST',body:'{}'});loadAll()}
async function addKeys(){let keys=document.getElementById('keys').value.split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean);await api('/api/keys',{method:'POST',body:JSON.stringify({keys,note:note.value})});document.getElementById('keys').value='';loadAll()}
async function removeKey(apiKey){if(confirm('Delete '+apiKey.slice(0,10)+'…?')){await api('/api/keys',{method:'DELETE',body:JSON.stringify({apiKey})});loadAll()}}
async function reactivate(apiKey){await api('/api/keys/reactivate',{method:'POST',body:JSON.stringify({apiKey})});loadAll()}
async function saveSettings(){await api('/api/settings',{method:'PUT',body:JSON.stringify({strategy:strategy.value,usageSyncIntervalSecs:+interval.value,maxNetworkFailures:+failures.value,quotaProbeLeadSecs:+lead.value})});loadAll()}
if(adminKey){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');loadAll()}
</script></body></html>`;
